name: Agent Scan

on:
  pull_request:
    types: [opened]

  workflow_dispatch:
    inputs:
      pr-number:
        description: "PR number to test against"
        required: true
        type: number

jobs:
  agent-scan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Run Agent Scan
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number || inputs.pr-number }}
